version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - ofds-network

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./configs/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - ofds-network
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # Tempo API
      #- "4317:4317"   # OTLP/gRPC
      #- "4318:4318"   # OTLP/HTTP
    networks:
      - ofds-network

  #jaeger:
  #  image: jaegertracing/jaeger:2.4.0
  #  container_name: jaeger
  #  command:
  #    - --set=receivers.otlp.protocols.grpc.endpoint="0.0.0.0:4317"
  #    - --set=receivers.otlp.protocols.http.endpoint="0.0.0.0:4318"
  #  ports:
  #    - "16686:16686" # Jaeger UI
  #    - "4317:4317"    # OLTP GRPC Receiver
  #    - "4318:4318"    # OLTP HTTP Receiver
  #    - "6831:6831/udp" # Tracing data
  #    - "14250:14250" # OTLP receiver
  #  networks:
  #    - ofds-network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - ofds-network
    depends_on:
      - loki

networks:
  ofds-network:
    name: ofds-network
    driver: bridge
