version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - ofds-network

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      # - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./configs/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - ofds-network
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # Tempo API
      #- "4317:4317"   # OTLP/gRPC
      #- "4318:4318"   # OTLP/HTTP
    networks:
      - ofds-network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ofds-network
    depends_on:
      - loki

networks:
  ofds-network:
    external: true

