{
 "title": "Demo Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prom-ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests per Minute by URI",
   "type": "timeseries",
   "description": "Displays the rate of incoming HTTP requests per minute, grouped by application and endpoint URI.\nHelps identify traffic distribution, detect high-traffic routes, and monitor application load in real-time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (application, uri) (\n  rate(http_server_requests_seconds_count{application!=\"api-gateway\", uri!~\"/actuator/prometheus|UNKNOWN\"}[1m])\n) * 60",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Orders Created over Time",
   "type": "timeseries",
   "description": "Visualizes the number of orders created over each 5-minute interval.\nIdeal for tracking order creation trends, observing bursts in order submissions, or correlating with marketing events and performance incidents.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(orders_created_total[5m])",
     "legendFormat": "orders"
    }
   ]
  },
  {
   "title": "Events Created per 15m",
   "type": "barchart",
   "description": "Shows the rate of order creations, deliveries created and completed over a rolling 15-minute window.\nUseful for understanding user activity patterns, spotting drops or spikes in order traffic, and capacity planning.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(deliveries_created_total[15m])",
     "legendFormat": "deliveries-created"
    },
    {
     "expr": "increase(deliveries_completed_total[15m])",
     "legendFormat": "deliveries-completed"
    },
    {
     "expr": "increase(orders_created_total[15m])",
     "legendFormat": "orders-created"
    }
   ]
  }
 ]
}