apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: "([a-f0-9]{32})"
          internalLink: true
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags: ["container_name"]
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{container_name="$${__container_name}", trace_id="$${__trace.trace_id}"}'
      serviceMap:
        datasourceUid: prometheus # tempo
      nodeGraph:
        enabled: true
      streamingEnabled:
        search: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: GET

  - name: Pyroscope
    type: phlare
    access: proxy
    uid: pyroscope
    url: http://pyroscope:4040
    isDefault: false
    editable: true
